### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by badmark** [sarthology/proGramCLI#1]
Installed and ran program. A box appeared with a dinosaur and a button 'Let's get started'. When pressed I believe it wants a folder as I cannot select a file, but once selected it just goes back to the let's get started screen.

Console shows no messages.

Also, description states 'self-hosted' but this appears to be an electron app. Any way to run this in the browser?

Arch Linux

**Comment by badmark** [comment]
Also, description for running development is incorrect:

Reads:
```

$ git clone https://github.com/sarthology/proGramCLI.git
$ cd proGramCLI
$ npm install
$ npm dev
```

Should Be:

```
$ git clone https://github.com/sarthology/proGramCLI.git
$ cd proGramCLI
$ npm install
$ npm run dev
```

**Comment by badmark** [comment]
In Development I do get the next screen, but if I select a profile picture, and then want to change it, it will not allow...

**Comment by metalx1000** [comment]
I can confirm everything badmark has said.
I'm running on a test machine, booting Linux Mint 19.1 off of a USB drive.
Using:
`$ npm i -g programcli
$ program`
results in the start screen and file dialog, but nothing happens after that.

Using GIT:
`$ git clone https://github.com/sarthology/proGramCLI.git
$ cd proGramCLI
$ npm install
$ npm run dev`
Things seem to be working, but the 'run' in 'npm run dev' is needed.

I also wonder if there is a way to run this on the server and open it in a browser.
This would be nice for mobile devices.
Although that may not be the goal of your project, it would be nice.

Also, once photos are uploaded, you have "See Files" and "Open in Browser",
It would be nice if there was a button to "Go Back" or "Close".

**Comment by pavanjadhaw** [comment]
Hey @badmark @badmark @sarthology and any other who has visited or faced this issue.

So as you would have noticed program works perfectly when run locally or during development,
but while publishing it to npm we forgot to include a vital file which npm should include by default unless stated in `.gitignore` or `.npmignore` which isnt the case.

I have fixed this issue in most recent commit(https://github.com/sarthology/proGramCLI/commit/57d685952332405b143ce8cf1c0e5dfb60a3d869) and npm package should work as expected after next republish.

Also thanks for pointing out the typo in development instructions in readme.
That as well is fixed in https://github.com/sarthology/proGramCLI/commit/b8c63a82ca8b6f80ef9d23732bba9988c9df39c0

Thanks for letting us know these major issues earlier.

**Comment by pavanjadhaw** [comment]
> Also, description states 'self-hosted' but this appears to be an electron app. Any way to run this in the browser?

@badmark programcli by default isnt meant to be hosted, as you would have notice it allows you to create profile and create posts which generates a minimal webpage which you can either run locally or self host on your server for others to see or deploy on any static web hosting services like github pages, netlify, surge or heroku to name a few

**Comment by sarthology** [comment]
@pavanjadhaw If it's fixed, please close the issue.

**Comment by jerpint** [comment]
I am facing the same issue pointed above and have installed using the latest version on npm...
